"""Génère un fichier de démonstration au format de Suivi_Licence.xlsx.

Utilisé uniquement si le fichier métier réel n'est pas disponible. Les dates sont
relatives à la date du jour pour avoir des échéances variées (expiré, critique, alerte, OK).
Le fichier contient volontairement des anomalies (doublon, date invalide, cellules vides,
formules) pour démontrer le rapport d'import.

Usage : python scripts/generate_demo_excel.py [chemin_sortie]
"""

import sys
from datetime import date, timedelta
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

T = date.today()
d = lambda days: T + timedelta(days=days)  # noqa: E731
HEAD = PatternFill("solid", fgColor="4F81BD")


def sheet(wb, name, title, headers, rows, days_col=None, end_letter=None):
    ws = wb.create_sheet(name)
    ws["A1"] = title
    ws["A1"].font = Font(bold=True, size=13)
    ws.append([])
    ws.append(headers)
    for c in ws[3]:
        c.font, c.fill = Font(bold=True, color="FFFFFF"), HEAD
    for i, r in enumerate(rows, start=4):
        r = list(r)
        if days_col is not None:
            r.insert(days_col, f'=IF({end_letter}{i}="","",{end_letter}{i}-TODAY())')
            r.insert(
                days_col + 1,
                f'=IF({end_letter}{i}="","",IF({end_letter}{i}-TODAY()<=0,"EXPIRÉ",IF({end_letter}{i}-TODAY()<=30,"CRITIQUE",IF({end_letter}{i}-TODAY()<=90,"ALERTE","OK"))))',
            )
        ws.append(r)
    for col in ws.columns:
        ws.column_dimensions[col[2].column_letter].width = 20
    return ws


def build(path: Path):
    wb = Workbook()
    wb.remove(wb.active)

    contracts = [
        (
            "CTR-2023-001",
            "AO-2023-12",
            "Microsoft France",
            "Julie Martin",
            "support@microsoft.fr",
            "01 23 45 67 89",
            "https://microsoft.com",
            "SaaS",
            "Microsoft 365 & Azure AD",
            "DSI - Poste de travail",
            d(-700),
            d(25),
            90,
            185000,
            "EUR",
            "Actif",
        ),
        (
            "CTR-2022-014",
            "MAPA-2022-08",
            "Oracle",
            "Paul Durand",
            "support@oracle.com",
            "01 40 00 00 00",
            "https://oracle.com",
            "Maintenance corrective/évolutive",
            "Support Oracle Database EE",
            "DSI - Infrastructure",
            d(-1000),
            d(75),
            180,
            96000,
            "EUR",
            "Actif",
        ),
        (
            "CTR-2024-003",
            "AO-2024-02",
            "Dell Technologies",
            "Marc Leroy",
            "pro.support@dell.com",
            "0 825 00 00 00",
            "https://dell.com",
            "Support constructeur",
            "ProSupport serveurs PowerEdge",
            "DSI - Infrastructure",
            d(-400),
            d(330),
            60,
            42000,
            "EUR",
            "Actif",
        ),
        (
            "CTR-2021-007",
            "AO-2021-05",
            "Sopra Steria",
            "Claire Bernard",
            "tma@soprasteria.com",
            "01 55 00 00 00",
            "https://soprasteria.com",
            "Prestation",
            "TMA applications métier RH/Finance",
            "DSI - Études",
            d(-1600),
            d(-15),
            120,
            310000,
            "EUR",
            "En renouvellement",
        ),
        (
            "CTR-2024-011",
            "UGAP-2024-01",
            "OVHcloud",
            "Service client",
            "support@ovhcloud.com",
            "1007",
            "https://ovhcloud.com",
            "Hébergement Cloud",
            "Hébergement plateforme web publique",
            "DSI - Infrastructure",
            d(-200),
            d(530),
            90,
            54000,
            "EUR",
            "Actif",
        ),
        (
            "CTR-2023-019",
            "MAPA-2023-11",
            "Adobe",
            "Service entreprise",
            "entreprise@adobe.com",
            "",
            "https://adobe.com",
            "SaaS",
            "Adobe Creative Cloud équipes communication",
            "Direction Communication",
            d(-300),
            d(12),
            30,
            18500,
            "EUR",
            "Actif",
        ),
        (
            "CTR-2022-021",
            "AO-2022-09",
            "Cisco Systems",
            "Nicolas Petit",
            "tac@cisco.com",
            "0800 00 00 00",
            "https://cisco.com",
            "Support constructeur",
            "SmartNet équipements réseau cœur",
            "DSI - Réseau",
            d(-900),
            d(160),
            90,
            67000,
            "EUR",
            "Actif",
        ),
        (
            "CTR-2024-025",
            "",
            "Sectigo",
            "",
            "support@sectigo.com",
            "",
            "https://sectigo.com",
            "SaaS",
            "Certificats SSL/TLS publics",
            "RSSI",
            d(-250),
            d(110),
            30,
            6200,
            "EUR",
            "Actif",
        ),
        (
            "CTR-2020-002",
            "AO-2020-01",
            "SAP France",
            "Isabelle Moreau",
            "support@sap.com",
            "01 46 00 00 00",
            "https://sap.com",
            "Maintenance corrective/évolutive",
            "Maintenance SAP ERP",
            "DSI - Études",
            d(-2000),
            d(-120),
            180,
            240000,
            "EUR",
            "Expiré - renouvellement en cours",
        ),
        (
            "CTR-2025-004",
            "AO-2025-03",
            "Atlassian",
            "",
            "support@atlassian.com",
            "",
            "https://atlassian.com",
            "SaaS",
            "Jira / Confluence Cloud",
            "DSI - Études",
            d(-100),
            d(265),
            60,
            28000,
            "EUR",
            "Actif",
        ),
        (
            "CTR-2023-019",
            "DOUBLON",
            "Adobe",
            "",
            "",
            "",
            "",
            "SaaS",
            "Ligne en doublon volontaire",
            "",
            d(-300),
            d(12),
            30,
            18500,
            "EUR",
            "Actif",
        ),
    ]
    sheet(
        wb,
        "Contrats_Fournisseurs",
        "Contrats fournisseurs",
        [
            "Référence contrat",
            "Réf. marché",
            "Fournisseur",
            "Contact",
            "Email support",
            "Téléphone",
            "Site web",
            "Type de contrat",
            "Périmètre",
            "Responsable interne",
            "Date de début",
            "Date de fin",
            "Préavis (jours)",
            "Montant annuel",
            "Devise",
            "Statut",
        ],
        contracts,
    )

    lic = [
        (
            "LIC-001",
            "Microsoft 365 E3",
            "Microsoft France",
            "Souscription",
            "",
            1200,
            1085,
            "CTR-2023-001",
            "J. Martin",
            "Toutes directions",
            d(-340),
            d(25),
            "Critique",
            165000,
            170000,
            "Lancer le renouvellement EA",
            "",
        ),
        (
            "LIC-002",
            "Windows Server Datacenter",
            "Microsoft France",
            "Perpétuelle avec abonnement",
            "XXXXX-XXXXX-WS22",
            40,
            32,
            "CTR-2023-001",
            "P. Durand",
            "DSI",
            d(-700),
            d(25),
            "Haute",
            20000,
            21000,
            "",
            "",
        ),
        (
            "LIC-003",
            "Oracle Database Enterprise",
            "Oracle",
            "Nommée",
            "",
            16,
            16,
            "CTR-2022-014",
            "P. Durand",
            "DSI",
            d(-1000),
            d(75),
            "Critique",
            96000,
            99000,
            "Audit des cœurs avant renouvellement",
            "Licences processeur",
        ),
        (
            "LIC-004",
            "Adobe Creative Cloud",
            "Adobe",
            "Souscription",
            "",
            25,
            19,
            "CTR-2023-019",
            "S. Laurent",
            "Direction Communication",
            d(-300),
            d(12),
            "Moyenne",
            18500,
            19000,
            "",
            "",
        ),
        (
            "LIC-005",
            "Jira Software Cloud",
            "Atlassian",
            "Souscription",
            "",
            300,
            248,
            "CTR-2025-004",
            "A. Roux",
            "DSI",
            d(-100),
            d(265),
            "Haute",
            21000,
            22000,
            "",
            "",
        ),
        (
            "LIC-006",
            "Confluence Cloud",
            "Atlassian",
            "Souscription",
            "",
            300,
            210,
            "CTR-2025-004",
            "A. Roux",
            "DSI",
            d(-100),
            d(265),
            "Moyenne",
            7000,
            7500,
            "",
            "",
        ),
        (
            "LIC-007",
            "AutoCAD",
            "Autodesk",
            "Flottante",
            "AC-77-1234",
            12,
            9,
            "",
            "M. Fabre",
            "Direction Patrimoine",
            d(-200),
            d(45),
            "Moyenne",
            24000,
            25000,
            "Évaluer passage licences nommées",
            "",
        ),
        (
            "LIC-008",
            "Veeam Backup & Replication",
            "Veeam",
            "Site",
            "",
            1,
            1,
            "",
            "P. Durand",
            "DSI",
            d(-500),
            d(-10),
            "Critique",
            15000,
            15500,
            "Commande en cours",
            "Licence expirée : risque sauvegardes",
        ),
        (
            "LIC-009",
            "VMware vSphere Enterprise Plus",
            "Broadcom",
            "Souscription",
            "",
            64,
            60,
            "",
            "P. Durand",
            "DSI",
            d(-365),
            d(140),
            "Critique",
            58000,
            75000,
            "Étudier alternatives (Proxmox, Hyper-V)",
            "Hausse tarifaire Broadcom",
        ),
        (
            "LIC-010",
            "SAP ERP utilisateurs",
            "SAP France",
            "Nommée",
            "",
            450,
            432,
            "CTR-2020-002",
            "I. Moreau",
            "Direction Financière",
            d(-2000),
            d(-120),
            "Critique",
            120000,
            130000,
            "Avenant en négociation",
            "",
        ),
        (
            "LIC-011",
            "Kaspersky Endpoint Security",
            "Kaspersky",
            "Souscription",
            "",
            1300,
            1150,
            "",
            "RSSI",
            "Toutes directions",
            d(-330),
            d(35),
            "Haute",
            22000,
            0,
            "Migration vers Defender for Endpoint",
            "",
        ),
        (
            "LIC-012",
            "Tableau Creator",
            "Salesforce",
            "Nommée",
            "",
            10,
            4,
            "",
            "B. Girard",
            "Direction Financière",
            d(-150),
            d(215),
            "Basse",
            9000,
            9000,
            "",
            "Sous-utilisée",
        ),
        (
            "LIC-013",
            "Zoom Workplace",
            "Zoom",
            "Souscription",
            "",
            50,
            12,
            "",
            "S. Laurent",
            "Direction Communication",
            d(-320),
            d(45),
            "Basse",
            7000,
            0,
            "Non renouveler : bascule Teams",
            "",
        ),
        (
            "LIC-014",
            "Visual Studio Enterprise",
            "Microsoft France",
            "Nommée",
            "",
            20,
            18,
            "CTR-2023-001",
            "A. Roux",
            "DSI",
            d(-340),
            "31/02/2027",
            "Moyenne",
            50000,
            52000,
            "",
            "Date invalide volontaire",
        ),
        (
            "LIC-004",
            "Adobe Creative Cloud (doublon)",
            "Adobe",
            "Souscription",
            "",
            25,
            19,
            "CTR-2023-019",
            "",
            "",
            d(-300),
            d(12),
            "",
            "",
            "",
            "",
            "Doublon volontaire",
        ),
        (
            "",
            "Notepad++",
            "",
            "Perpétuelle avec abonnement",
            "",
            500,
            None,
            "",
            "",
            "DSI",
            None,
            None,
            "Basse",
            0,
            0,
            "",
            "Gratuit — référence manquante",
        ),
        (
            "LIC-015",
            "ArcGIS Pro",
            "Esri France",
            "Flottante",
            "",
            8,
            11,
            "",
            "M. Fabre",
            "Direction Patrimoine",
            d(-90),
            d(275),
            "Moyenne",
            16000,
            16000,
            "",
            "Plus d'utilisateurs que de licences !",
        ),
        ("", "", "", "", "", None, None, "", "", "", None, None, "", None, None, "", "ligne sans référence ni nom"),
    ]
    # colonnes : Réf, Logiciel, Editeur, Type, Clé, Nb licences, Utilisées, Contrat, Responsable, Direction, Début, Expiration(L), [Jours, Statut], Criticité, Coût, Budget, Plan, Obs
    sheet(
        wb,
        "Licences_Logicielles",
        "Suivi des licences logicielles",
        [
            "Réf.",
            "Logiciel",
            "Editeur",
            "Type de licence",
            "Clé de licence",
            "Nb licences",
            "Utilisées",
            "Contrat",
            "Responsable",
            "Direction",
            "Date de début",
            "Date d'expiration",
            "Criticité",
            "Coût annuel (€)",
            "Budget estimé (€)",
            "Plan d'action",
            "Observations",
        ],
        lic,
    )
    ws = wb["Licences_Logicielles"]
    ws.insert_cols(13, 2)
    ws.cell(row=3, column=13, value="Jours restants").font = Font(bold=True)
    ws.cell(row=3, column=14, value="Statut").font = Font(bold=True)
    for i in range(4, 4 + len(lic)):
        ws.cell(row=i, column=13, value=f'=IF(L{i}="","",L{i}-TODAY())')
        ws.cell(
            row=i,
            column=14,
            value=f'=IF(L{i}="","",IF(L{i}-TODAY()<=0,"EXPIRÉ",IF(L{i}-TODAY()<=30,"CRITIQUE",IF(L{i}-TODAY()<=90,"ALERTE","OK"))))',
        )

    certs = [
        (
            "CERT-001",
            "*.exemple-collectivite.fr",
            "Wildcard",
            "Sectigo",
            "Reverse proxy / portails",
            "Production",
            "Sectigo",
            "CTR-2024-025",
            "RSSI",
            "DSI",
            d(-340),
            d(22),
            "Critique",
            1200,
            1300,
            "Commander renouvellement",
            "",
        ),
        (
            "CERT-002",
            "www.exemple-collectivite.fr",
            "SSL/TLS",
            "Let's Encrypt",
            "Site institutionnel",
            "Production",
            "",
            "",
            "Équipe Web",
            "Direction Communication",
            d(-60),
            d(30),
            "Haute",
            0,
            0,
            "Renouvellement auto certbot",
            "",
        ),
        (
            "CERT-003",
            "vpn.exemple-collectivite.fr",
            "SSL/TLS",
            "Sectigo",
            "Passerelle VPN",
            "Production",
            "Sectigo",
            "CTR-2024-025",
            "RSSI",
            "DSI",
            d(-300),
            d(65),
            "Critique",
            350,
            350,
            "",
            "",
        ),
        (
            "CERT-004",
            "intranet.local",
            "Certificat interne",
            "PKI interne AD CS",
            "Intranet",
            "Production",
            "",
            "",
            "P. Durand",
            "DSI",
            d(-700),
            d(-5),
            "Moyenne",
            0,
            0,
            "Régénérer via PKI",
            "Expiré",
        ),
        (
            "CERT-005",
            "api.exemple-collectivite.fr",
            "SSL/TLS",
            "Sectigo",
            "API Gateway",
            "Production",
            "Sectigo",
            "CTR-2024-025",
            "A. Roux",
            "DSI",
            d(-200),
            d(165),
            "Haute",
            350,
            350,
            "",
            "",
        ),
        (
            "CERT-006",
            "recette.exemple-collectivite.fr",
            "SSL/TLS",
            "Let's Encrypt",
            "Serveur recette",
            "Recette",
            "",
            "",
            "A. Roux",
            "DSI",
            d(-80),
            d(8),
            "Basse",
            0,
            0,
            "",
            "",
        ),
        (
            "CERT-007",
            "mail.exemple-collectivite.fr",
            "SSL/TLS",
            "DigiCert",
            "Exchange OWA",
            "Production",
            "DigiCert",
            "",
            "P. Durand",
            "DSI",
            d(-250),
            "N/A",
            "Critique",
            450,
            450,
            "",
            "Date à compléter",
        ),
        (
            "CERT-008",
            "Signature code DSI",
            "Certificat interne",
            "PKI interne AD CS",
            "Scripts PowerShell",
            "Production",
            "",
            "",
            "RSSI",
            "DSI",
            d(-400),
            d(400),
            "Basse",
            0,
            0,
            "",
            "",
        ),
    ]
    sheet(
        wb,
        "Certificats",
        "Suivi des certificats",
        [
            "Référence",
            "Domaine",
            "Type de certificat",
            "Autorité",
            "Serveur / Application cible",
            "Environnement",
            "Fournisseur",
            "Contrat",
            "Responsable",
            "Direction",
            "Date d'émission",
            "Date d'expiration",
            "Criticité",
            "Coût annuel",
            "Budget",
            "Plan d'action",
            "Observations",
        ],
        certs,
    )

    mats = [
        (
            "MAT-001",
            "Serveur ESX 01",
            "Dell",
            "PowerEdge R750",
            "SN-7XK21",
            "Datacenter principal",
            "Dell Technologies",
            "CTR-2024-003",
            "P. Durand",
            "DSI",
            d(-900),
            d(-900 + 365 * 3),
            d(330),
            "ProSupport 4h",
            "Critique",
            4500,
            5000,
            "",
            "",
        ),
        (
            "MAT-002",
            "Serveur ESX 02",
            "Dell",
            "PowerEdge R750",
            "SN-7XK22",
            "Datacenter principal",
            "Dell Technologies",
            "CTR-2024-003",
            "P. Durand",
            "DSI",
            d(-900),
            d(-900 + 365 * 3),
            d(330),
            "ProSupport 4h",
            "Critique",
            4500,
            5000,
            "",
            "",
        ),
        (
            "MAT-003",
            "Baie stockage SAN",
            "NetApp",
            "AFF A250",
            "NA-551203",
            "Datacenter principal",
            "NetApp",
            "",
            "P. Durand",
            "DSI",
            d(-1500),
            d(-400),
            d(55),
            "SupportEdge",
            "Critique",
            18000,
            22000,
            "Prévoir remplacement / extension",
            "",
        ),
        (
            "MAT-004",
            "Cœur de réseau",
            "Cisco",
            "Catalyst 9500",
            "FOC2231X0AB",
            "Datacenter principal",
            "Cisco Systems",
            "CTR-2022-021",
            "N. Petit",
            "DSI",
            d(-1200),
            d(-100),
            d(160),
            "SmartNet 8x5xNBD",
            "Critique",
            9000,
            9500,
            "",
            "",
        ),
        (
            "MAT-005",
            "Pare-feu périmétrique",
            "Fortinet",
            "FortiGate 200F",
            "FG200FTK2201",
            "Datacenter principal",
            "Fortinet",
            "",
            "RSSI",
            "DSI",
            d(-700),
            d(-335),
            d(28),
            "FortiCare 24x7",
            "Critique",
            7000,
            7500,
            "Renouveler FortiCare + UTM",
            "",
        ),
        (
            "MAT-006",
            "Switchs d'étage (lot 24)",
            "HPE Aruba",
            "2930F",
            "Lot",
            "Hôtel de ville",
            "HPE",
            "",
            "N. Petit",
            "DSI",
            d(-2200),
            d(-500),
            d(-30),
            "",
            "Moyenne",
            0,
            60000,
            "Renouvellement parc 2027",
            "Fin de support atteinte",
        ),
        (
            "MAT-007",
            "Imprimantes multifonctions",
            "Ricoh",
            "IM C3000",
            "Lot 35",
            "Tous sites",
            "Ricoh France",
            "",
            "Services généraux",
            "Direction Générale",
            d(-600),
            "",
            d(495),
            "Location maintenance",
            "Basse",
            28000,
            28000,
            "",
            "",
        ),
        (
            "MAT-008",
            "Onduleur salle serveur",
            "APC",
            "Smart-UPS SRT 10kVA",
            "AS1922112345",
            "Datacenter principal",
            "Schneider Electric",
            "",
            "P. Durand",
            "DSI",
            d(-1800),
            d(-1070),
            None,
            "",
            "Haute",
            0,
            8000,
            "Remplacement batteries",
            "Pas de contrat de support",
        ),
        (
            "MAT-009",
            "Bornes Wi-Fi",
            "HPE Aruba",
            "AP-515",
            "Lot 60",
            "Tous sites",
            "HPE",
            "",
            "N. Petit",
            "DSI",
            d(-400),
            d(700),
            d(700),
            "Garantie à vie limitée",
            "Moyenne",
            0,
            0,
            "",
            "",
        ),
        (
            "MAT-010",
            "Serveur sauvegarde",
            "HPE",
            "ProLiant DL380 Gen10",
            "CZJ0123ABC",
            "Site secours",
            "HPE",
            "",
            "P. Durand",
            "DSI",
            d(-1300),
            d(-200),
            d(85),
            "Foundation Care",
            "Haute",
            2500,
            2600,
            "",
            "",
        ),
    ]
    sheet(
        wb,
        "Materiels",
        "Inventaire matériels",
        [
            "N° inventaire",
            "Désignation",
            "Marque",
            "Modèle",
            "N° série",
            "Site",
            "Fournisseur",
            "Contrat",
            "Responsable",
            "Direction",
            "Date d'acquisition",
            "Fin de garantie",
            "Fin de support",
            "Type de contrat support",
            "Criticité",
            "Coût annuel",
            "Budget estimé",
            "Plan d'action",
            "Observations",
        ],
        mats,
    )

    apps = [
        (
            "APP-001",
            "SAP ERP Finance",
            "Direction Financière",
            "I. Moreau",
            "Direction Financière",
            "On-premise",
            "Sopra Steria",
            "SAP France",
            "CTR-2020-002",
            "99,5% - J+1",
            d(-3000),
            d(-120),
            "Critique",
            240000,
            250000,
            "Négociation avenant",
            "",
        ),
        (
            "APP-002",
            "SIRH Paie",
            "Direction RH",
            "C. Bernard",
            "Direction RH",
            "SaaS",
            "Sopra Steria",
            "Sopra Steria",
            "CTR-2021-007",
            "99,5%",
            d(-1600),
            d(-15),
            "Critique",
            85000,
            90000,
            "Relancer procédure de marché",
            "",
        ),
        (
            "APP-003",
            "Portail citoyen",
            "Direction Communication",
            "Équipe Web",
            "Direction Communication",
            "Cloud OVH",
            "OVHcloud",
            "OVHcloud",
            "CTR-2024-011",
            "99,9%",
            d(-500),
            d(530),
            "Haute",
            54000,
            54000,
            "",
            "",
        ),
        (
            "APP-004",
            "Gestion Électronique de Documents",
            "Direction Générale",
            "A. Roux",
            "Toutes directions",
            "On-premise",
            "",
            "Alfresco",
            "",
            "Best effort",
            d(-1400),
            d(80),
            "Moyenne",
            32000,
            35000,
            "",
            "",
        ),
        (
            "APP-005",
            "Messagerie Exchange Online",
            "DSI",
            "J. Martin",
            "Toutes directions",
            "SaaS",
            "Microsoft",
            "Microsoft France",
            "CTR-2023-001",
            "99,9%",
            d(-800),
            d(25),
            "Critique",
            0,
            0,
            "Inclus M365",
            "",
        ),
        (
            "APP-006",
            "Outil de ticketing GLPI",
            "DSI",
            "A. Roux",
            "DSI",
            "On-premise",
            "Teclib'",
            "Teclib'",
            "",
            "J+1",
            d(-900),
            d(200),
            "Moyenne",
            8000,
            8000,
            "",
            "",
        ),
        (
            "APP-007",
            "Application urbanisme",
            "Direction Urbanisme",
            "M. Fabre",
            "Direction Urbanisme",
            "SaaS",
            "",
            "Berger-Levrault",
            "CTR-2026-099",
            "99%",
            d(-700),
            d(60),
            "Haute",
            26000,
            27000,
            "",
            "Contrat non référencé dans l'onglet contrats",
        ),
    ]
    sheet(
        wb,
        "Applications",
        "Portefeuille applicatif",
        [
            "Référence",
            "Application",
            "Propriétaire métier",
            "Responsable technique",
            "Direction",
            "Hébergement",
            "Prestataire",
            "Editeur",
            "Contrat",
            "SLA",
            "Date de mise en service",
            "Date de fin de contrat",
            "Criticité",
            "Coût annuel",
            "Budget estimé",
            "Plan d'action",
            "Commentaires",
        ],
        apps,
    )

    ws = wb.create_sheet("Planning_Renouvellement")
    ws.append(["Planning des renouvellements (calculé)"])
    ws.append(["Référence", "Échéance", "Responsable"])
    ws.append(["LIC-001", d(25), "J. Martin"])
    ws = wb.create_sheet("Dashboard")
    ws.append(["Tableau de bord"])
    ws.append(["Total licences", "=COUNTA(Licences_Logicielles!A4:A100)"])

    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parents[2] / "data" / "Suivi_Licence.xlsx"
    print(build(out))
