"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 10:21:40.528042
"""

from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("rows_analyzed", sa.Integer(), nullable=False),
        sa.Column("rows_imported", sa.Integer(), nullable=False),
        sa.Column("rows_skipped", sa.Integer(), nullable=False),
        sa.Column("warnings_count", sa.Integer(), nullable=False),
        sa.Column("errors_count", sa.Integer(), nullable=False),
        sa.Column("report", sa.Text(), nullable=True),
        sa.Column("imported_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("target_reference", sa.String(length=100), nullable=True),
        sa.Column("target_name", sa.String(length=255), nullable=True),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("days_remaining", sa.Integer(), nullable=False),
        sa.Column("recipients", sa.Text(), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("delivery_status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_type", "target_id", "threshold", "due_date", name="uq_notification"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "vendors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contact_person", sa.String(length=255), nullable=True),
        sa.Column("email_support", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendors_name"), "vendors", ["name"], unique=True)
    op.create_table(
        "contracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("market_ref", sa.String(length=100), nullable=True),
        sa.Column("vendor_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=100), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("internal_owner", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notice_period_days", sa.Integer(), nullable=True),
        sa.Column("annual_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("attachment_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contracts_end_date"), "contracts", ["end_date"], unique=False)
    op.create_index(op.f("ix_contracts_reference"), "contracts", ["reference"], unique=True)
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=True),
        sa.Column("contract_id", sa.Integer(), nullable=True),
        sa.Column("internal_owner", sa.String(length=255), nullable=True),
        sa.Column("user_department", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("criticality", sa.String(length=50), nullable=True),
        sa.Column("annual_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("budget_estimated", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("action_plan", sa.Text(), nullable=True),
        sa.Column("observation", sa.Text(), nullable=True),
        sa.Column("lic_type", sa.String(length=100), nullable=True),
        sa.Column("license_key", sa.String(length=500), nullable=True),
        sa.Column("total_quantity", sa.Integer(), nullable=True),
        sa.Column("cert_type", sa.String(length=100), nullable=True),
        sa.Column("authority", sa.String(length=255), nullable=True),
        sa.Column("server_app_target", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=100), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("serial_number", sa.String(length=255), nullable=True),
        sa.Column("site_location", sa.String(length=255), nullable=True),
        sa.Column("warranty_end_date", sa.Date(), nullable=True),
        sa.Column("support_end_date", sa.Date(), nullable=True),
        sa.Column("support_contract_type", sa.String(length=255), nullable=True),
        sa.Column("business_owner", sa.String(length=255), nullable=True),
        sa.Column("hosting_env", sa.String(length=255), nullable=True),
        sa.Column("service_provider", sa.String(length=255), nullable=True),
        sa.Column("sla_level", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category", "reference", name="uq_asset_category_reference"),
    )
    op.create_index(op.f("ix_assets_category"), "assets", ["category"], unique=False)
    op.create_index(op.f("ix_assets_end_date"), "assets", ["end_date"], unique=False)
    op.create_index(op.f("ix_assets_name"), "assets", ["name"], unique=False)
    op.create_index(op.f("ix_assets_reference"), "assets", ["reference"], unique=False)
    op.create_index(op.f("ix_assets_user_department"), "assets", ["user_department"], unique=False)
    op.create_table(
        "license_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_user", sa.String(length=255), nullable=True),
        sa.Column("assigned_to_device", sa.String(length=255), nullable=True),
        sa.Column("assigned_to_department", sa.String(length=255), nullable=True),
        sa.Column("assigned_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_license_assignments_asset_id"),
        "license_assignments",
        ["asset_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_license_assignments_asset_id"), table_name="license_assignments")
    op.drop_table("license_assignments")
    op.drop_index(op.f("ix_assets_user_department"), table_name="assets")
    op.drop_index(op.f("ix_assets_reference"), table_name="assets")
    op.drop_index(op.f("ix_assets_name"), table_name="assets")
    op.drop_index(op.f("ix_assets_end_date"), table_name="assets")
    op.drop_index(op.f("ix_assets_category"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_contracts_reference"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_end_date"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_vendors_name"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("notifications")
    op.drop_table("import_logs")
    # ### end Alembic commands ###
